import { EProjectInvitationStatus, EProjectRequestStatus, EProjectRoles } from "../../utils/enums"
import { EUserRoles } from "../../utils/enums"
import { EGenders } from "../../utils/enums"
import type {
  TGeneralSearchData,
  TNotificationData,
  TPhaseData,
  TProjectInvitationData,
  TProjectMemberData,
  TProjectRequestData,
  TSearchUserData,
  TTaskMemberData,
} from "../types"

const taskMembers: TTaskMemberData[] = [
  {
    id: 1,
    avatar: "https://trello-logos.s3.amazonaws.com/7c17ee5f87fa99637dce66430e395d97/170.png",
    fullName: "full codevcn",
    email: "demo-email@mail.ru",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.ADMIN,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 2,
    avatar: null,
    fullName: "Lala",
    email: "demo-email@maim.rv",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 3,
    avatar: null,
    fullName: "Lulu",
    email: "demo-email@main.rw",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 4,
    avatar:
      "https://trello-members.s3.amazonaws.com/65b078657d14de9327fcae56/a0cea1a61f9f6f57630a7aeb1f97f679/170.png",
    fullName: "lele vcn",
    email: "demo-email@maio.rx",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 5,
    avatar: null,
    fullName: "Thu Quan Hong Quan",
    email: "demo-email@maip.ry",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 6,
    avatar:
      "https://trello-members.s3.amazonaws.com/65b078657d14de9327fcae56/ca97615375a67bd83bbca24966bf87e7/170.png",
    fullName: "Lam Chan Anh",
    email: "demo-email@maiq.rz",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 7,
    avatar: null,
    fullName: "Baba",
    email: "demo-email@mair.sa",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 8,
    avatar: null,
    fullName: "Baba 2",
    email: "demo-email@mais.sb",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
]

const phases: TPhaseData[] = [
  {
    id: 1,
    title: "Todo",
    position: 0,
    description: "desc 1",
    taskPreviews: [
      {
        id: 1,
        title: "Lời mở đầu 1",
        hasDescription: true,
        position: 0,
        taskMembers: taskMembers.slice(0, 5),
        status: "uncomplete",
        dueDate: "2025-02-14T09:45:11.925653Z",
      },
      {
        id: 3,
        title: "Mẫu giao diện 1",
        hasDescription: true,
        position: 1,
        taskMembers: null,
        status: "uncomplete",
        dueDate: "2025-02-16T09:45:11.925653Z",
      },
    ],
  },
  {
    id: 2,
    title: "In Progress",
    position: 1,
    description: "desc 2",
    taskPreviews: [
      {
        id: 4,
        title: "Lời mở đầu 2",
        hasDescription: true,
        position: 0,
        taskMembers: null,
        status: "uncomplete",
        dueDate: null,
      },
      {
        id: 5,
        title: "Web to do okay? vcn",
        hasDescription: true,
        position: 1,
        taskMembers: taskMembers.slice(0, 4),
        status: "uncomplete",
        dueDate: "2025-02-14T09:45:11.925653Z",
      },
      {
        id: 6,
        title: "Mẫu giao diện 2",
        hasDescription: true,
        position: 2,
        taskMembers: null,
        status: "uncomplete",
        dueDate: "2025-01-05T08:39:41.890Z",
      },
      {
        id: 99,
        title: "Mẫu giao diện 3",
        hasDescription: true,
        position: 3,
        taskMembers: null,
        status: "uncomplete",
        dueDate: "2025-03-15T09:45:11.925653Z",
      },
      {
        id: 101,
        title: "Mẫu giao diện 4",
        hasDescription: true,
        position: 4,
        taskMembers: taskMembers.slice(5, 8),
        status: "uncomplete",
        dueDate: "2025-01-07T08:39:41.890Z",
      },
      {
        id: 105,
        title: "Mẫu giao diện 5",
        hasDescription: true,
        position: 5,
        taskMembers: taskMembers.slice(3, 6),
        status: "uncomplete",
        dueDate: "2025-02-16T09:45:11.925653Z",
      },
      {
        id: 102,
        title: "Mẫu giao diện 6",
        hasDescription: true,
        position: 6,
        taskMembers: null,
        status: "uncomplete",
        dueDate: "2025-03-15T09:45:11.925653Z",
      },
      {
        id: 103,
        title: "Mẫu giao diện 7",
        hasDescription: true,
        position: 7,
        taskMembers: null,
        status: "uncomplete",
        dueDate: "2025-02-16T09:45:11.925653Z",
      },
    ],
  },
  {
    id: 3,
    title: "Complete",
    position: 2,
    description: "desc 3",
    taskPreviews: [
      {
        id: 11,
        title: "Lời mở đầuLời mở đầuLời mở đầuLời mở đầuLời mở đầuLời mở đầuLời mở đầu",
        hasDescription: true,
        position: 0,
        taskMembers: null,
        status: "uncomplete",
        dueDate: null,
      },
    ],
  },
  {
    id: 4,
    title: "Done",
    position: 3,
    description: "desc 4",
    taskPreviews: [
      {
        id: 9,
        title: "Lời mở đầu 3",
        hasDescription: true,
        position: 0,
        taskMembers: null,
        status: "uncomplete",
        dueDate: "2025-01-12T08:39:41.890Z",
      },
    ],
  },
  {
    id: 5,
    title: "Need Help",
    position: 4,
    description: "desc 5",
    taskPreviews: [
      {
        id: 10,
        title: "Lời mở đầu 4",
        hasDescription: true,
        position: 0,
        taskMembers: null,
        status: "uncomplete",
        dueDate: null,
      },
      {
        id: 20,
        title: "Phân tích & Thiết kế",
        hasDescription: true,
        position: 1,
        taskMembers: null,
        status: "uncomplete",
        dueDate: "2025-02-20T09:45:11.925653Z",
      },
    ],
  },
]

const notifications: TNotificationData[] = [
  {
    id: 1,
    description: "Hoa Ho wants to join the Workspace Personal CodeVCN.",
    timestamp: "2025-02-06T17:41:00Z",
    seen: false,
  },
  {
    id: 2,
    description: "Reminder: Was due Feb 5, 2025, 3:16 PM",
    timestamp: "2025-02-04T15:16:00Z",
    seen: false,
  },
  {
    id: 3,
    description: "A new system update is available. Please restart your app.",
    timestamp: "2025-02-07T08:30:00Z",
    seen: true,
  },
  {
    id: 4,
    description: "Don't forget to submit your project report before the deadline.",
    timestamp: "2025-02-06T12:00:00Z",
    seen: false,
  },
]

const generalSearchData: TGeneralSearchData = {
  projects: [
    {
      id: 1,
      title: "Project Management App",
      background:
        "https://trello-backgrounds.s3.amazonaws.com/SharedBackground/2560x1703/6f971f0ef48c1a5f2cde86f2d3a9ab56/photo-1736297150541-89378f055b96.webp",
    },
    {
      id: 2,
      title: "E-commerce Platform",
      background:
        "https://trello-backgrounds.s3.amazonaws.com/SharedBackground/2560x1703/6f971f0ef48c1a5f2cde86f2d3a9ab56/photo-1736297150541-89378f055b96.webp",
    },
    {
      id: 3,
      title: "Social Media Dashboard",
      background:
        "https://trello-backgrounds.s3.amazonaws.com/SharedBackground/2401x1600/ceca11e134be93c2bf61b61bd285fc6f/photo-1691929601779-ead6aeb78d1b.jpg",
    },
  ],
  phases: [
    { id: 1, title: "Planning", project: { title: "Project Management App", id: 1 } },
    { id: 2, title: "Development", project: { title: "Project Management App", id: 1 } },
    { id: 3, title: "Testing", project: { title: "Project Management App", id: 1 } },
    { id: 4, title: "Design", project: { title: "E-commerce Platform", id: 2 } },
    { id: 5, title: "Deployment", project: { title: "Social Media Dashboard", id: 2 } },
  ],
  tasks: [
    {
      id: 1,
      title: "Setup Database",
      project: { title: "Project Management App", id: 1 },
      phase: { title: "Planning", id: 2 },
    },
    {
      id: 2,
      title: "Design UI Components",
      project: { title: "Project Management App", id: 1 },
      phase: { title: "Development", id: 4 },
    },
    {
      id: 3,
      title: "Fix Login Bugs",
      project: { title: "Project Management App", id: 1 },
      phase: { title: "Testing", id: 5 },
    },
    {
      id: 4,
      title: "Create Product Listing Page",
      project: { title: "E-commerce Platform", id: 1 },
      phase: { title: "Design", id: 1 },
    },
    {
      id: 5,
      title: "Optimize Checkout Process",
      project: { title: "E-commerce Platform", id: 2 },
      phase: { title: "Development", id: 5 },
    },
    {
      id: 6,
      title: "Deploy to Production",
      project: { title: "Social Media Dashboard", id: 2 },
      phase: { title: "Deployment", id: 1 },
    },
  ],
}

const staticUsers: TSearchUserData[] = [
  {
    id: 9,
    avatar: null,
    fullName: "Bimmmmmmmmmmmmm 123",
    email: "demo-email@mait.sc",
    role: EUserRoles.USER,
  },
  {
    id: 10,
    avatar: "https://trello-logos.s3.amazonaws.com/7c17ee5f87fa99637dce66430e395d97/170.png",
    fullName: "Lala 123",
    email: "email222@mail.ru",
    role: EUserRoles.ADMIN,
  },
  {
    id: 11,
    avatar: null,
    fullName: "Bimmmmmmmmmmmmm 123",
    email: "demo-email@mait.sc",
    role: EUserRoles.USER,
  },
  {
    id: 12,
    avatar: "https://trello-logos.s3.amazonaws.com/7c17ee5f87fa99637dce66430e395d97/170.png",
    fullName: "UUU",
    email: "UUU@xxx.ssss",
    role: EUserRoles.USER,
  },
]

const projectMembers: TProjectMemberData[] = [
  {
    id: 1,
    avatar: "https://trello-logos.s3.amazonaws.com/7c17ee5f87fa99637dce66430e395d97/170.png",
    fullName: "full codevcn",
    email: "demo-email@mail.ru",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.ADMIN,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 2,
    avatar: null,
    fullName: "Lala",
    email: "demo-email@maim.rv",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 3,
    avatar: null,
    fullName: "Lulu",
    email: "demo-email@main.rw",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 4,
    avatar:
      "https://trello-members.s3.amazonaws.com/65b078657d14de9327fcae56/a0cea1a61f9f6f57630a7aeb1f97f679/170.png",
    fullName: "lele vcn",
    email: "demo-email@maio.rx",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 5,
    avatar: null,
    fullName: "Thu Quan Hong Quan",
    email: "demo-email@maip.ry",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 6,
    avatar:
      "https://trello-members.s3.amazonaws.com/65b078657d14de9327fcae56/ca97615375a67bd83bbca24966bf87e7/170.png",
    fullName: "Lam Chan Anh",
    email: "demo-email@maiq.rz",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 7,
    avatar: null,
    fullName: "Baba",
    email: "demo-email@mair.sa",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 8,
    avatar: null,
    fullName: "Baba 2",
    email: "demo-email@mais.sb",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
  {
    id: 9,
    avatar: null,
    fullName: "Bimmmmmmmmmmmmm 123",
    email: "demo-email@mait.sc",
    role: EUserRoles.USER,
    projectRole: EProjectRoles.MEMBER,
    bio: "A full-stack developer passionate about minimalism and efficiency. Always looking for ways to optimize workflows for maximum productivity!",
    birthday: "2000-02-02",
    gender: EGenders.MALE,
    socialLinks: "github.com/minhhuydev",
    emailVerified: true,
  },
]

const projectInvitations: TProjectInvitationData[] = [
  {
    id: 1,
    projectId: 101,
    sender: { id: 1001 },
    receiver: {
      id: 2001,
      fullName: "Nguyễn Văn A",
      email: "nguyenvana@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectInvitationStatus.PENDING,
    sendAt: "2025-02-24T10:30:00Z",
  },
  {
    id: 2,
    projectId: 102,
    sender: { id: 1002 },
    receiver: {
      id: 2002,
      fullName: "Trần Thị B",
      email: "tranthib@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectInvitationStatus.ACCEPTED,
    sendAt: "2025-02-23T14:15:00Z",
  },
  {
    id: 3,
    projectId: 103,
    sender: { id: 1003 },
    receiver: {
      id: 2003,
      fullName: "Lê Văn C",
      email: "levanc@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectInvitationStatus.DECLINED,
    sendAt: "2025-02-22T08:45:00Z",
  },
  {
    id: 4,
    projectId: 104,
    sender: { id: 1004 },
    receiver: {
      id: 2004,
      fullName: "Phạm Thị D",
      email: "phamthid@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectInvitationStatus.PENDING,
    sendAt: "2025-02-21T12:00:00Z",
  },
  {
    id: 5,
    projectId: 105,
    sender: { id: 1005 },
    receiver: {
      id: 2005,
      fullName: "Hoàng Văn E",
      email: "hoangvane@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectInvitationStatus.ACCEPTED,
    sendAt: "2025-02-20T09:20:00Z",
  },
  {
    id: 6,
    projectId: 106,
    sender: { id: 1006 },
    receiver: {
      id: 2006,
      fullName: "Đỗ Thị F",
      email: "dothif@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectInvitationStatus.DECLINED,
    sendAt: "2025-02-19T16:40:00Z",
  },
  {
    id: 7,
    projectId: 107,
    sender: { id: 1007 },
    receiver: {
      id: 2007,
      fullName: "Ngô Văn G",
      email: "ngovang@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectInvitationStatus.PENDING,
    sendAt: "2025-02-18T11:10:00Z",
  },
  {
    id: 8,
    projectId: 108,
    sender: { id: 1008 },
    receiver: {
      id: 2008,
      fullName: "Bùi Thị H",
      email: "buithih@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectInvitationStatus.ACCEPTED,
    sendAt: "2025-02-17T13:25:00Z",
  },
  {
    id: 9,
    projectId: 109,
    sender: { id: 1009 },
    receiver: {
      id: 2009,
      fullName: "Dương Văn I",
      email: "duongvani@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectInvitationStatus.DECLINED,
    sendAt: "2025-02-16T15:55:00Z",
  },
  {
    id: 10,
    projectId: 110,
    sender: { id: 1010 },
    receiver: {
      id: 2010,
      fullName: "Vũ Thị J",
      email: "vuthij@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectInvitationStatus.PENDING,
    sendAt: "2025-02-15T07:30:00Z",
  },
]

const projectRequests: TProjectRequestData[] = [
  {
    id: 1,
    projectId: 101,
    sender: {
      id: 1001,
      fullName: "Nguyễn Văn A",
      email: "nguyenvana@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectRequestStatus.PENDING,
    sendAt: "2025-02-24T10:30:00Z",
  },
  {
    id: 2,
    projectId: 102,
    sender: {
      id: 1002,
      fullName: "Trần Thị B",
      email: "tranthib@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectRequestStatus.ACCEPTED,
    sendAt: "2025-02-23T14:15:00Z",
  },
  {
    id: 3,
    projectId: 103,
    sender: {
      id: 1003,
      fullName: "Lê Văn C",
      email: "levanc@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectRequestStatus.DECLINED,
    sendAt: "2025-02-22T08:45:00Z",
  },
  {
    id: 4,
    projectId: 104,
    sender: {
      id: 1004,
      fullName: "Phạm Thị D",
      email: "phamthid@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectRequestStatus.PENDING,
    sendAt: "2025-02-21T12:00:00Z",
  },
  {
    id: 5,
    projectId: 105,
    sender: {
      id: 1005,
      fullName: "Hoàng Văn E",
      email: "hoangvane@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectRequestStatus.ACCEPTED,
    sendAt: "2025-02-20T09:20:00Z",
  },
  {
    id: 6,
    projectId: 106,
    sender: {
      id: 1006,
      fullName: "Đỗ Thị F",
      email: "dothif@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectRequestStatus.DECLINED,
    sendAt: "2025-02-19T16:40:00Z",
  },
  {
    id: 7,
    projectId: 107,
    sender: {
      id: 1007,
      fullName: "Ngô Văn G",
      email: "ngovang@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectRequestStatus.PENDING,
    sendAt: "2025-02-18T11:10:00Z",
  },
  {
    id: 8,
    projectId: 108,
    sender: {
      id: 1008,
      fullName: "Bùi Thị H",
      email: "buithih@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectRequestStatus.ACCEPTED,
    sendAt: "2025-02-17T13:25:00Z",
  },
  {
    id: 9,
    projectId: 109,
    sender: {
      id: 1009,
      fullName: "Dương Văn I",
      email: "duongvani@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectRequestStatus.DECLINED,
    sendAt: "2025-02-16T15:55:00Z",
  },
  {
    id: 10,
    projectId: 110,
    sender: {
      id: 1010,
      fullName: "Vũ Thị J",
      email: "vuthij@example.com",
      avatar: "https://gravatar.com/avatar/ae1a3a4e0759ad91eafc212b7f887ab7?s=400&d=robohash&r=x",
    },
    status: EProjectRequestStatus.PENDING,
    sendAt: "2025-02-15T07:30:00Z",
  },
]
